# Generated by Django 2.1.3 on 2018-12-13 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VenueReview',
        ),
    ]
