# Generated by Django 2.1.3 on 2018-12-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0002_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default=False, upload_to='images/events'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='image',
            field=models.ImageField(default=False, upload_to='images/venues'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
