# Generated by Django 2.1.3 on 2018-12-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0003_auto_20181205_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default=False, max_length=400),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='artist',
            name='events',
        ),
        migrations.AddField(
            model_name='artist',
            name='events',
            field=models.ManyToManyField(to='webtech.Event'),
        ),
        migrations.RemoveField(
            model_name='genre',
            name='events',
        ),
        migrations.AddField(
            model_name='genre',
            name='events',
            field=models.ManyToManyField(to='webtech.Event'),
        ),
    ]
