# Generated by Django 2.1.3 on 2018-12-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0004_auto_20181205_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='bio',
        ),
        migrations.AddField(
            model_name='artist',
            name='last_fm_entry_exists',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
