# Generated by Django 2.1.3 on 2018-12-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0005_auto_20181205_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
