# Generated by Django 2.1.3 on 2018-12-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0006_event_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
