# Generated by Django 2.1.3 on 2018-12-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0008_auto_20181206_0821'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='Preview',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='links',
            new_name='previews',
        ),
        migrations.AddField(
            model_name='event',
            name='official_page',
            field=models.CharField(default='google.com', max_length=100),
            preserve_default=False,
        ),
    ]
