# Generated by Django 2.1.3 on 2018-12-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0009_auto_20181206_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='official_page',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='preview',
            name='url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address_string',
            field=models.CharField(max_length=200),
        ),
    ]
