# Generated by Django 2.1.3 on 2018-12-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0015_auto_20181206_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
