# Generated by Django 2.1.3 on 2018-12-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0016_auto_20181206_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.CharField(max_length=3000),
        ),
    ]
