# Generated by Django 2.1.3 on 2018-12-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0017_auto_20181207_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
