# Generated by Django 2.1.2 on 2018-12-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0021_auto_20181209_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='last_fm_entry_exists',
            field=models.BooleanField(default=False),
        ),
    ]
