# Generated by Django 2.1.3 on 2018-12-15 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0022_venuereview_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='reviews',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webtech.VenueReview'),
            preserve_default=False,
        ),
    ]
