# Generated by Django 2.1.3 on 2018-12-15 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0023_venue_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='reviews',
        ),
        migrations.AddField(
            model_name='venuereview',
            name='venue',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webtech.Venue'),
            preserve_default=False,
        ),
    ]
