# Generated by Django 2.1.3 on 2018-12-15 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0025_auto_20181215_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuereview',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
