# Generated by Django 2.1.3 on 2018-12-05 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='webtech.Event')),
            ],
        ),
    ]
