# Generated by Django 2.1.3 on 2018-12-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0007_auto_20181205_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='links',
            field=models.ManyToManyField(to='webtech.Link'),
        ),
    ]
