# Generated by Django 2.1.3 on 2018-12-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0010_auto_20181206_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
