# Generated by Django 2.1.3 on 2018-12-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0013_auto_20181206_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='genres',
            field=models.ManyToManyField(to='webtech.Genre'),
        ),
        migrations.AlterField(
            model_name='event',
            name='official_page',
            field=models.CharField(max_length=300),
        ),
    ]
