# Generated by Django 2.1.3 on 2018-12-06 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0014_auto_20181206_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtech.Venue'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
