# Generated by Django 2.1.3 on 2018-12-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0020_auto_20181208_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='official_page',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='preview',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address_string',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='venuereview',
            name='text',
            field=models.TextField(),
        ),
    ]
