# Generated by Django 2.1.2 on 2018-12-15 17:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models
from django.contrib.gis.geos.point import Point


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0023_auto_20181214_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='address_string',
            new_name='adress_fr',
        ),
        migrations.AddField(
            model_name='venue',
            name='address_nl',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='venue',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=Point(50.8467139, 4.3524994), srid=4326),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='official_page',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
