# Generated by Django 2.1.2 on 2018-12-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0024_auto_20181215_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Venue',
            old_name='adress_fr',
            new_name='address_fr',
        ),
    ]
