# Generated by Django 2.1.3 on 2018-12-15 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0024_auto_20181215_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuereview',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='webtech.Venue'),
        ),
    ]
