# Generated by Django 2.1.2 on 2018-12-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0025_auto_20181215_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='address_fr',
            field=models.TextField(default=''),
        ),
    ]
