# Generated by Django 2.1.3 on 2018-12-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0026_venuereview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='image',
            field=models.ImageField(upload_to='images/uploaded'),
        ),
    ]
