# Generated by Django 2.1.3 on 2018-12-15 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0027_auto_20181215_1731'),
        ('webtech', '0028_auto_20181215_1825'),
    ]

    operations = [
    ]
