# Generated by Django 2.1.3 on 2018-12-16 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtech', '0030_auto_20181216_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='events',
            field=models.ManyToManyField(related_name='artists', to='webtech.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='genres',
            field=models.ManyToManyField(related_name='events', to='webtech.Genre'),
        ),
        migrations.AlterField(
            model_name='event',
            name='previews',
            field=models.ManyToManyField(related_name='events', to='webtech.Preview'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='webtech.Venue'),
        ),
    ]
